export {
  resolveAppHome,
  resolvePostAuthDestination,
  destinationAfterAuth,
  destinationAfterEmailLink,
  isSafeNextPath,
  isCustomerSurfacePath,
  isPasswordUpdatePath,
  isRecoveryAuthType,
  workspaceLabel,
  OPERATOR_HOME_PATH,
  STORE_HOME_PATH,
  CUSTOMER_HOME_PATH,
  PASSWORD_UPDATE_PATH,
  type AppHomePath,
} from "@findit/domain";
